name: Testes do front-end usando selenium

on:
  workflow_dispatch:
  push: # gatilho para executar o fluxo quando houver um push para o repositório
    branches: [ $default-branch ]  
  pull_request:
    branches: [ main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Selenium # instala as dependências necessárias para executar os testes
      run: npm install -g selenium-side-runner
    - name: Install chrome # executa os testes usando o comando 'npm run test'
      run: npm install -g chromedriver
    - name: Run Tests
      run: npx selenium-side-runner --browser chrome ./midall.side
